name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: ./backend
      - name: Lint
        run: npm run lint
        working-directory: ./backend
      - name: Test
        run: npm test
        working-directory: ./backend
